name: Other
description: questions,bug reports,etc
body:
- type: textarea
  attributes:
    label: text
    description: your text
    placeholder: |
      your text
  validations:
    required: false
