name: Serverlist form
description: Add a paid,27/7 or replit eaglercraft server
title: "server name"
body:
- type: checkboxes
  attributes:
    label: by making a request to add your server you must check these boxes
    options:
    - label: I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
      required: true
    - label: I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
      required: true
    - label: I know that by making a request to add my server to the serverlist anyone can join my server
      required: true
    - label: I know that by making a request you dont make me a server and add it to the serverlist
      required: true
    - label: I just checked all of these boxes without reading the labels
      required: false
- type: checkboxes
  attributes:
    label: replit server or 24/7 eaglercraft server?
    description: is the eaglercraft server made in replit or a paid,24/7 host? do NOT select both options or i cant add the server to the serverlist
    options:
    - label: the server is made in replit
      required: false
    - label: the server is made in an paid,24/7 host
      required: false
- type: textarea
  attributes:
    label: about server
    description: write at least 1 line about your server
    placeholder: |
      online time, plugins, gamemodes,etc
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: at least 2 or 3 screenshots of the server (not required)
    placeholder: |
      screenshots of the server
  validations:
    required: false
- type: input
  attributes:
    label: Discord/revolt server
    description: discord/revolt invite (not required)
  validations:
    required: false
- type: input
  attributes:
    label: server's website
    description: the website of the server (not required)
  validations:
    required: false
    
- type: input
  attributes:
    label: server ip
    description: the ip of the server. please put eaglercraft ip not minecraft. the ip should start with "wss://" if it dosnt it CANT be added to the serverlist
  validations:
    required: true
